/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageencrytion;

import java.awt.Component;
import java.io.File;
import javax.crypto.Cipher;
import javax.crypto.KeyGenerator;
import javax.crypto.SecretKey;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Simran Bansal
 */
public class ImageE extends javax.swing.JFrame {

    /**
     * Creates new form ImageE
     */
    
    File file;
    String path;
    String fileName;
    KeyGenerator keygenerator;
    SecretKey secKey;
    SecretKey secretKey;
    Cipher cipher;
    String aesKey;
    String fileToEncrypt;
    String encryptedFile="encryptedFile.jpg";
    String decryptedFile="decryptedFile.jpg";
    String directoryPath="C:/Temp/ImageEncryption/";
    
    
    public ImageE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        browserbutton = new javax.swing.JButton();
        uploadbutton = new javax.swing.JButton();
        generatebutton = new javax.swing.JButton();
        encryptbutton = new javax.swing.JButton();
        nextbutton = new javax.swing.JButton();
        homebutton = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        lb2.setForeground(new java.awt.Color(0, 255, 255));
        lb2.setText("IMAGE ENCRYPTION");
        jPanel1.add(lb2);
        lb2.setBounds(280, 40, 370, 60);

        lb3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 0));
        lb3.setText("Choose Image:");
        jPanel1.add(lb3);
        lb3.setBounds(80, 150, 140, 60);

        lb4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lb4.setForeground(new java.awt.Color(255, 255, 0));
        lb4.setText("Secret Key:");
        jPanel1.add(lb4);
        lb4.setBounds(90, 250, 130, 50);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(240, 160, 520, 40);

        browserbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        browserbutton.setText("Browser");
        browserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browserbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(browserbutton);
        browserbutton.setBounds(790, 160, 130, 40);

        uploadbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        uploadbutton.setText("Upload");
        uploadbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(uploadbutton);
        uploadbutton.setBounds(110, 380, 150, 50);

        generatebutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        generatebutton.setText("Generate Key");
        generatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(generatebutton);
        generatebutton.setBounds(320, 380, 170, 50);

        encryptbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        encryptbutton.setText("Encrypt");
        encryptbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(encryptbutton);
        encryptbutton.setBounds(550, 380, 130, 50);

        nextbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/next.png"))); // NOI18N
        nextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(nextbutton);
        nextbutton.setBounds(750, 380, 50, 50);

        homebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.PNG"))); // NOI18N
        homebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebuttonActionPerformed(evt);
            }
        });
        jPanel1.add(homebutton);
        homebutton.setBounds(860, 30, 60, 50);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(240, 250, 520, 40);

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t2.jpg"))); // NOI18N
        jPanel1.add(lb1);
        lb1.setBounds(0, 0, 960, 530);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 961, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void homebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebuttonActionPerformed
        // TODO add your handling code here:
        Main1 m=new Main1();
        m.setVisible(true);
    }//GEN-LAST:event_homebuttonActionPerformed

    private void nextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbuttonActionPerformed
        // TODO add your handling code here:
        ImageD id=new ImageD(aesKey,path);
        id.setVisible(true);
    }//GEN-LAST:event_nextbuttonActionPerformed

    private void browserbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browserbuttonActionPerformed
        // TODO add your handling code here:
        JFileChooser fi=new JFileChooser();
        Component jPanel=null;
        fi.showOpenDialog(jPanel);
        file=fi.getSelectedFile();
        fileName= fi.getName(file);
        path=file.getAbsolutePath();
        System.out.println("the image from browser button "+ path);
        jTextField1.setText(path);
        System.out.println("the filename is "+fileName);
    }//GEN-LAST:event_browserbuttonActionPerformed

    private void encryptbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptbuttonActionPerformed
        // TODO add your handling code here:
        String destPath=directoryPath+encryptedFile;
        String destpath;
        System.out.println("the source path "+ path);
        System.out.println("the destination path"+ destPath);
        ImageEncryption ie=new ImageEncryption();
        ie.encrypt(path, destPath);
        JOptionPane.showMessageDialog(null, "image encryption completed");
    }//GEN-LAST:event_encryptbuttonActionPerformed

    private void generatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatebuttonActionPerformed
        // TODO add your handling code here:
        KeyGenerator generator=null;
        try{
            generator=KeyGenerator.getInstance("AES");
            generator.init(256);          // AES key size in number of bits
            
            secKey = generator.generateKey();
            secretKey=generator.generateKey();
            cipher= Cipher.getInstance("AES");
            
            String secKey1=secKey.toString();
            String [] key=secKey1.split("@");
            String aeskey=key[1];
            aesKey=key[1];
            JOptionPane.showMessageDialog(null,"Random Key Generated");
            jTextField2.setText(aeskey);
          
        }
        catch(Exception ex)
                {
                    ex.printStackTrace();
                }
        
        
        
    }//GEN-LAST:event_generatebuttonActionPerformed

    private void uploadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadbuttonActionPerformed
        // TODO add your handling code here:
        OriginalImage oriImage=new OriginalImage(path);
        oriImage.setVisible(true);
        
    }//GEN-LAST:event_uploadbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImageE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browserbutton;
    private javax.swing.JButton encryptbutton;
    private javax.swing.JButton generatebutton;
    private javax.swing.JButton homebutton;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JButton nextbutton;
    private javax.swing.JButton uploadbutton;
    // End of variables declaration//GEN-END:variables
}
