/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageencrytion;

import javax.swing.JOptionPane;

/**
 *
 * @author Simran Bansal
 */
public class ImageD extends javax.swing.JFrame {

    /**
     * Creates new form ImageD
     */
    
    String decKey;
    String encryptedFile="encryptedFile.jpg";
    String decryptedFile="decryptedFile.jpg";
    String  directoryPath="C:/Temp/ImageEncryption/";
    String imagePath;
    public ImageD(String aesKey,String actualKey) {
        decKey = aesKey;
        imagePath=actualKey;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb2 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        getkeybutton = new javax.swing.JButton();
        decryptkeybutton = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        lb2.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        lb2.setForeground(new java.awt.Color(0, 255, 255));
        lb2.setText("IMAGE DECRYPTION");
        jPanel1.add(lb2);
        lb2.setBounds(320, 40, 470, 80);

        lb3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lb3.setForeground(new java.awt.Color(255, 255, 0));
        lb3.setText("Secret Key:");
        jPanel1.add(lb3);
        lb3.setBounds(90, 170, 150, 70);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(270, 170, 560, 60);

        getkeybutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getkeybutton.setText("Get Key");
        getkeybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getkeybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(getkeybutton);
        getkeybutton.setBounds(290, 320, 190, 60);

        decryptkeybutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        decryptkeybutton.setText("Decrypt");
        decryptkeybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptkeybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(decryptkeybutton);
        decryptkeybutton.setBounds(580, 320, 150, 60);

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t2.jpg"))); // NOI18N
        jPanel1.add(lb1);
        lb1.setBounds(0, 0, 1070, 540);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1070, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void decryptkeybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptkeybuttonActionPerformed
        // TODO add your handling code here:
        String test=jTextField1.getText();
        if(test.equals("")){
            JOptionPane.showMessageDialog(null, "Please Get SecretKey");
            
            
        }
        else if(!test.equals(decKey)){
            JOptionPane.showMessageDialog(null,"Given SecretKey is Wrong");
        } 
        else{
            String src= directoryPath+encryptedFile;
            String dest="C:/Temp/imageEncryption/decryption.jpg";
            ImageEncryption ie=new ImageEncryption();
            ie.decrypt(src, dest);
            JOptionPane.showMessageDialog(null, "image decryption completed");
            DecryptImage deImage=new DecryptImage(imagePath);
            deImage.setVisible(true);
        }
    }//GEN-LAST:event_decryptkeybuttonActionPerformed

    private void getkeybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getkeybuttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(decKey);
    }//GEN-LAST:event_getkeybuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new ImageD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decryptkeybutton;
    private javax.swing.JButton getkeybutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    // End of variables declaration//GEN-END:variables
}
