/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageencrytion;

import static imageencrytion.TextE.cipher;
import java.security.Key;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.NativeRegExp.test;
import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

/**
 *
 * @author Simran Bansal
 */
public class TextD extends javax.swing.JFrame {

    /**
     * Creates new form TextD
     */
    String encryptMsg;
    SecretKey key;
    String aeskey;
    public TextD(String encText,SecretKey sKey) {
        encryptMsg=encText;
        key=sKey;
        String secKey1=key.toString();
        String[] key1=secKey1.split("@");
        aeskey = key1[1];
        System.out.println("the encrypted message from TEXTD "+encryptMsg);
        
        
        
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        viewencrypttextbutton = new javax.swing.JButton();
        getkeybutton = new javax.swing.JButton();
        decryptbutton = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("TEXT DECRYPTION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 0, 290, 80);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Cipher Text:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 110, 120, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Secret Key:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 210, 110, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Original Message:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 290, 150, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 90, 430, 90);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(300, 210, 440, 40);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(300, 280, 440, 60);

        viewencrypttextbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewencrypttextbutton.setText("View Encrypt Text");
        viewencrypttextbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewencrypttextbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(viewencrypttextbutton);
        viewencrypttextbutton.setBounds(90, 400, 250, 30);

        getkeybutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getkeybutton.setText("Get Key");
        getkeybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getkeybuttonActionPerformed(evt);
            }
        });
        jPanel1.add(getkeybutton);
        getkeybutton.setBounds(390, 400, 110, 30);

        decryptbutton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        decryptbutton.setText("Decrypt");
        decryptbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(decryptbutton);
        decryptbutton.setBounds(640, 400, 110, 31);

        lb1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/t2.jpg"))); // NOI18N
        jPanel1.add(lb1);
        lb1.setBounds(0, 0, 840, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void getkeybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getkeybuttonActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(aeskey);
        
    }//GEN-LAST:event_getkeybuttonActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setEditable(false);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void decryptbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptbuttonActionPerformed
        // TODO add your handling code here:
        String test=jTextField1.getText();
        if (test.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Get SecretKey");
            
        }
        if(!test.equals(aeskey))
        {
            JOptionPane.showMessageDialog(null,"Given SecretKey is Wrong");
        }
        else
        {
            try{
                String Data=jTextArea1.getText();
           Cipher c=Cipher.getInstance("AES");
               
           c.init(Cipher.DECRYPT_MODE, key);
          byte[] decordedValue=new BASE64Decoder().decodeBuffer(encryptMsg);
          byte[] decValue=c.doFinal(decordedValue);
          String decryptedText=new String (decValue);
          JOptionPane.showMessageDialog(null, "The Text Decryption is completed");
           
            jTextArea2.append(decryptedText);
            }
            catch(Exception e){
               e. printStackTrace();
                
            }
        }
    }//GEN-LAST:event_decryptbuttonActionPerformed

    private void viewencrypttextbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewencrypttextbuttonActionPerformed
        // TODO add your handling code here:
        jTextArea1.append(encryptMsg);
    }//GEN-LAST:event_viewencrypttextbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TextD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TextD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TextD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TextD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new TextD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton decryptbutton;
    private javax.swing.JButton getkeybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lb1;
    private javax.swing.JButton viewencrypttextbutton;
    // End of variables declaration//GEN-END:variables
}
